feat(01-building-blocks): added workflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -4,17 +4,17 @@ on: push
 
 jobs:
   echo-hello:
-    runs-on: ubuntu-lastest
+    runs-on: ubuntu-latest
     steps:
         - name: Say hello
           run: echo "Hello World!"
   echo-goodbye: 
     runs-on: ubuntu-latest
     steps:
-        - name: Successful step
+        - name: Failed step
           run: |
-               echo "I will succeed"
-               exit 0
+               echo "I will fail"
+               exit 1
         - name: Say Goodbye
           run: echo "Goodbye!"        
                
