Feat(15-matrices.yaml): Adding code for matrix

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -8,15 +8,30 @@ jobs:
         name: ${{ matrix.os }}-${{ matrix.node-version }}
         runs-on: ${{matrix.os}}
         strategy:
+            # if it true then any job will fail it will encrypt other jobs and fail then other job also get exceute even one is failed
+            fail-fast: true
             matrix: 
                  node-version: [18.x, 20.x, 21.x]
                  os:
                     - ubuntu-latest
                     - windows-latest
+                 include:
+                    - os: ubuntu-latest
+                      node-version: 16.x
+                    - os: ubuntu-latest
+                      node-version: 21.x
+                      tag: experimental     
         steps:
             - name: Setup node
               uses: actions/setup-node@v3
               with: 
-                node-version: ${{ matrix.node-version }}                  
+                node-version: ${{ matrix.node-version }}
+            - name: Fail if experimental
+              if: matrix.tag == 'experimental'
+              run : exit 1 
             - name: Perform some tests
-              run: echo "Running tests on OS ${{matrix.os}} and NodeJS ${{ matrix.node-version }}"   
+              run: |
+                echo "Running tests on OS ${{matrix.os}} and NodeJS ${{ matrix.node-version }}" 
+                sleep 10  
+            - name: Upload test results
+              run: echo "Uploading test results"     
